[package]
name = "mir-repr"
version = "0.1.0"
edition.workspace = true

[lints]
workspace = true

[dependencies]
hir-repr = { version = "0.1.0", path = "../hir-repr" }
la-arena.workspace = true
smallvec = "1.15.1"