[package]
name = "analyzer"
version = "0.1.0"
edition.workspace = true

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
ariadne.workspace = true
log.workspace = true
la-arena.workspace = true
repr = { version = "0.1.0", path = "../repr" }
