//! The ASTs - Abstract Syntax Trees - generated by tree-sitter along with their
//! corresponding source codes after preprocessing.
//!

/// Contains [`AST`]s properties.
mod ast;
/// Contains functions used for preprocessing source code.
mod preprocess;

pub use ast::AST;
