[package]
name = "cli"
version = "0.1.0"
edition.workspace = true

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
clap = { version = "4.5.30", features = ["derive"] }
clap_derive = "4.5.28"
