[package]
name = "cli-utils"
version = "0.1.0"
edition.workspace = true

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
compile_commands.workspace = true
clap = { version = "4.5.41", features = ["derive"] }
clap_derive = "4.5.41"
serde = "1.0.218"
serde_json = "1.0.139"

