[package]
name = "hir-repr"
version = "0.1.0"
edition.workspace = true

[lints]
workspace = true

[dependencies]
log.workspace = true
anyhow.workspace = true
tree-sitter.workspace = true
la-arena.workspace = true
ast-utils = { version = "0.1.0", path = "../ast-utils" }
