name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy-check:
    strategy:
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.88.0
        components: rustfmt, clippy
        override: true

    - name: Install just
      run: cargo install just

    - name: Check code style
      run: just check-format

    - name: Check clippy lints
      run: just clippy
